---
apiVersion: v1
kind: Namespace
metadata:
  name: flower-worker

---
apiVersion: v1
kind: Pod
metadata:
  name: flower-worker
  namespace: flower-worker
  labels:
    name: flower-worker
spec:
  containers:
  - name: flower-worker
    image: local/takke/flower:v1.0
    env:
      - name: CELERY_AMQP_URL
        value: 'pyamqp://takke:takke@rabbitmq-stateless.rabbitmq-stateless:5672/'
      - name: CELERY_BACKEND_URL
        value: 'redis://redis-stateless.redis-stateless:6379/0'
      #- name: MY_IP
       #   valueFrom:
        #    fieldRef:
         #     fieldPath: status.podIP

    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - name: flowermonitor
        containerPort: 5555

---
apiVersion: v1
kind: Service
metadata:
  name: flower-worker
  namespace: flower-worker
  labels:
    name: flower-worker
spec:
  #type: NodePort
  ports:
    - name: flowermonitor
      port: 5555
      targetPort: 5555
  selector:
    name: flower-worker