---
apiVersion: v1
kind: Namespace
metadata:
  name: celery-worker-rc
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: celery-worker-rc
  namespace: celery-worker-rc
spec:
  replicas: 10
  selector:
    app: celery-worker-rc
  template:
    metadata:
      name: celery-worker-rc
      labels:
        app: celery-worker-rc
    spec:
      containers:
      - name: celery-worker-rc
        image: local/takke/celery:v1.0
        env:
          - name: CELERY_AMQP_URL
            value: 'pyamqp://takke:takke@rabbitmq-stateless.rabbitmq-stateless:5672/'
          - name: CELERY_BACKEND_URL
            value: 'redis://redis-stateless.redis-stateless:6379/0'
