---
apiVersion: v1
kind: Namespace
metadata:
  name: celery-worker

---
apiVersion: v1
kind: Pod
metadata:
  name: celery-worker
  namespace: celery-worker
  labels:
    name: celery-worker
spec:
  containers:
  - name: celery-worker
    image: local/takke/celery:v1.0
    env:
      - name: CELERY_AMQP_URL
        value: 'pyamqp://takke:takke@rabbitmq-stateless.rabbitmq-stateless:5672/'
      - name: CELERY_BACKEND_URL
        value: 'redis://redis-stateless.redis-stateless:6379/0'
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
  