---
apiVersion: v1
kind: Namespace
metadata:
  name: redis-stateless

---
apiVersion: v1
kind: Pod
metadata:
  name: redis-stateless
  namespace: redis-stateless
  labels:
    name: redis-stateless
spec:
  containers:
  - name: redis-stateless
    image: redis:7.0-rc1
    env:
      - name: ALLOW_EMPTY_PASSWORD
        value: yes
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - name: db
        containerPort: 7000
        protocol: TCP
      

---
apiVersion: v1
kind: Service
metadata:
  name: redis-stateless
  namespace: redis-stateless
  labels:
    name: redis-stateless
spec:
  #type: NodePort
  ports:
    - name: management
      port: 7000
      targetPort: 7000
      #nodePort: 31111
  selector:
    name: redis-stateless
