---
apiVersion: v1
kind: Namespace
metadata:
  name: rabbitmq-stateless

---
apiVersion: v1
kind: Pod
metadata:
  name: rabbitmq-stateless
  namespace: rabbitmq-stateless
  labels:
    name: rabbitmq-stateless
spec:
  containers:
  - name: rabbitmq-stateless
    image: rabbitmq:3.9.13-management
    env:
      - name: RABBITMQ_DEFAULT_USER
        value: takke
      - name: RABBITMQ_DEFAULT_PASS
        value: takke
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - name: management
        containerPort: 15672
        protocol: TCP
      - name: amqp
        containerPort: 5672
        protocol: TCP


---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-stateless
  namespace: rabbitmq-stateless
  labels:
    name: rabbitmq-stateless
spec:
  #type: NodePort
  ports:
    - name: management
      port: 15672
      targetPort: 15672
      #nodePort: 31111
    - name: amqp
      port: 5672
      targetPort: 5672
      protocol: TCP
      #nodePort: 31112
  selector:
    name: rabbitmq-stateless
